# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Matthew Boyd | Portfolio
# Description of the Site
description: Matthew's Personal Projet, Blog and CV site. 
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: Site_BG.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: matthewboydd04@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: MatthewBoyd04
github_username:  MatthewBoyd04
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: matt_boyd

# Name of the Author
author-name: Matthew Boyd
# URL for the Image of the Author
author-image: Site_BG.jpg
# 60 Words About the Author
author-about: Hi, I'm Matt, currently in my 4th and final year at the University of Sheffield, Interning at amazon as a L4 SDE. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/MatthewBoyd04
# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
